import spacy
import random
import os
from typing import List, Dict, Optional, Set

class SafeTopicFilter:
    """
    A Python script that implements the 'Safe Humor' protocol filter.
    It uses natural language processing to detect controversial topics and
    automatically flags them, suggesting they be reframed in terms of
    sandwiches or quantum ducks.
    """

    # A simplified list of potentially controversial keywords.
    # In a real-world scenario, this would be much more extensive,
    # potentially using a machine learning model trained on a large corpus
    # or a more sophisticated topic modeling approach.
    CONTROVERSIAL_KEYWORDS: Set[str] = {
        "politics", "religion", "sex", "violence", "death", "hate",
        "discrimination", "war", "crime", "disease", "money", "debt",
        "taxes", "controversy", "argument", "dispute", "conflict",
        "racism", "gender", "sexual", "abuse", "terror", "crisis",
        "poverty", "famine", "epidemic", "scandal", "protest", "riot",
        "election", "government", "party", "ideology", "belief",
        "faith", "god", "allah", "jesus", "buddha", "muhammad",
        "murder", "rape", "assault", "bomb", "weapon", "drugs",
        "alcoholism", "addiction", "suicide", "depression", "anxiety",
        "trauma", "victim", "perpetrator", "justice", "injustice",
        "oppression", "freedom", "rights", "equality", "inequality",
        "capitalism", "socialism", "communism", "fascism", "anarchy",
        "revolution", "coup", "dictator", "tyrant", "monarchy",
        "republic", "democracy", "autocracy", "theocracy",
        "abortion", "euthanasia", "cloning", "genetics", "ethics",
        "morality", "philosophy", "existentialism", "nihilism",
        "atheism", "agnosticism", "spirituality", "cult", "sect",
        "conspiracy", "hoax", "fake news", "propaganda", "censorship",
        "surveillance", "privacy", "data", "hacking", "cybersecurity",
        "climate change", "global warming", "pollution", "environment",
        "extinction", "species", "conservation", "sustainability",
        "nuclear", "radiation", "disaster", "catastrophe", "tragedy",
        "famine", "drought", "flood", "earthquake", "tsunami",
        "volcano", "asteroid", "alien", "ufo", "paranormal", "ghost",
        "demon", "angel", "heaven", "hell", "satan", "devil",
        "magic", "witchcraft", "occult", "superstition", "curse",
        "blessing", "miracle", "prophecy", "destiny", "fate",
        "karma", "reincarnation", "nirvana", "enlightenment", "awakening",
        "meditation", "yoga", "mindfulness", "zen", "tao", "buddhism",
        "hinduism", "judaism", "christianity", "islam", "sikhism",
        "paganism", "wicca", "voodoo", "santeria", "shamanism",
        "ancestor", "spirit", "soul", "aura", "chakra", "kundalini",
        "astrology", "horoscope", "tarot", "numerology", "palmistry",
        "fortune telling", "psychic", "medium", "clairvoyance",
        "telepathy", "telekinesis", "levitation", "invisibility",
        "immortality", "vampire", "werewolf", "zombie", "goblin",
        "elf", "fairy", "dragon", "unicorn", "mermaid", "sphinx",
        "griffin", "phoenix", "minotaur", "centaur", "cyclops",
        "gorgon", "harpy", "siren", "chimera", "hydra", "kraken",
        "leviathan", "behemoth", "cerberus", "medusa", "goliath",
        "titan", "giant", "ogre", "troll", "dwarf", "gnome",
        "leprechaun", "banshee", "poltergeist", "specter",
        "phantom", "wraith", "spirit", "demon", "devil", "satan",
        "lucifer", "beezlebub", "asmodeus", "belial", "mammon",
        "lilith", "succubus", "incubus", "frankenstein",
        "dracula", "jason", "freddy", "chucky", "pinhead", "leatherface",
        "scream", "halloween", "nightmare", "exorcist", "omen",
        "conjuring", "insidious", "hereditary", "midsommar",
        "blair witch", "ring", "grudge", "it", "clown", "doll",
        "puppet", "ventriloquist", "serial killer", "mass murderer",
        "cannibal", "torture", "mutilation", "gore", "blood",
        "guts", "flesh", "bone", "corpse", "cadaver", "skeleton",
        "skull", "grave", "cemetery", "funeral", "mourning",
        "grief", "loss", "bereavement", "widow", "orphan",
        "homeless", "refugee", "migrant", "asylum", "deportation",
        "border", "wall", "fence", "prison", "jail", "convict",
        "felon", "criminal", "gang", "mafia", "cartel", "smuggling",
        "trafficking", "kidnapping", "ransom", "hostage", "extortion",
        "blackmail", "bribery", "corruption", "embezzlement", "fraud",
        "scam", "forgery", "perjury", "libel", "slander", "defamation",
        "harassment", "stalking", "bullying", "neglect",
        "exploitation", "coercion", "manipulation", "gaslighting",
        "brainwashing", "indoctrination", "misinformation",
        "disinformation", "post-truth", "alternative facts",
        "echo chamber", "filter bubble", "polarization", "extremism",
        "radicalization", "terrorism", "insurgency", "guerrilla",
        "rebellion", "uprising", "mutiny", "sedition", "treason",
        "espionage", "sabotage", "assassination", "coup d'etat",
        "civil war", "genocide", "ethnic cleansing", "holocaust",
        "atrocity", "massacre", "pogrom", "lynching", "execution",
        "capital punishment", "death penalty", "imprisonment",
        "solitary confinement", "gulag", "concentration camp",
        "slavery", "indentured servitude", "human trafficking",
        "child labor", "sweatshop", "wage theft",
        "union busting", "strike breaking", "lockout", "boycott",
        "sanctions", "embargo", "tariff", "trade war", "currency war",
        "economic crisis", "recession", "depression", "inflation",
        "deflation", "stagflation", "hyperinflation", "bankruptcy",
        "foreclosure", "eviction", "homelessness",
        "wealth gap", "class struggle", "social justice",
        "affirmative action", "reparations", "privilege", "systemic racism",
        "white supremacy", "nazism", "nationalism", "globalism",
        "multiculturalism", "assimilation", "integration", "segregation",
        "apartheid", "colonialism", "imperialism", "post-colonialism",
        "decolonization", "indigenous", "native", "aboriginal", "first nations",
        "settler", "colonizer", "oppressor", "oppressed",
        "survivor", "resilience", "resistance", "activism",
        "demonstration", "march", "rally", "strike",
        "civil disobedience", "nonviolence", "pacifism", "militarism",
        "warfare", "combat", "battle", "siege", "invasion",
        "occupation", "annexation", "conquest", "empire", "hegemony",
        "superpower", "cold war", "proxy war", "guerrilla war",
        "cyberwarfare", "space war", "arms race", "disarmament",
        "peace treaty", "ceasefire", "armistice", "negotiation",
        "diplomacy", "blockade", "humanitarian crisis", "refugee crisis", "migrant crisis",
        "meteor", "comet", "solar flare", "black hole", "dark matter",
        "dark energy", "multiverse", "parallel universe", "time travel",
        "wormhole", "warp drive", "teleportation", "extraterrestrial",
        "seti", "first contact", "terraforming",
        "robot", "android", "cyborg", "ai", "artificial intelligence",
        "singularity", "transhumanism", "post-human", "genetic engineering",
        "designer baby", "eugenics", "cryonics", "mind uploading",
        "virtual reality", "augmented reality", "metaverse",
        "simulation", "matrix", "dystopia", "utopia", "apocalypse",
        "post-apocalyptic", "survival", "prepper", "doomsday",
        "cataclysm", "extinction event", "asteroid impact",
        "supervolcano", "ice age", "sea level rise", "ocean acidification",
        "deforestation", "desertification", "smog", "acid rain",
        "ozone depletion", "nuclear waste", "toxic waste",
        "plastic pollution", "microplastics", "overpopulation",
        "resource depletion", "water scarcity", "food insecurity",
        "pandemic", "virus", "bacteria", "fungus", "parasite",
        "vaccine", "antiviral", "antibiotic", "superbug", "bioterrorism",
        "germ warfare", "chemical warfare", "biological weapon", "nuclear weapon",
        "mass destruction", "WMD", "arms control", "non-proliferation",
        "aggression", "hostility", "enmity", "bigotry",
        "prejudice", "sexism", "homophobia", "transphobia", "ableism",
        "ageism", "xenophobia", "islamophobia", "antisemitism", "misogyny",
        "misandry", "chauvinism", "jingoism", "patriotism", "loyalty",
        "betrayal", "disloyalty", "insurrection",
        "chaos", "disorder", "turmoil", "unrest",
        "emergency", "calamity", "misfortune", "adversity",
        "hardship", "suffering", "pain", "grief", "sorrow",
        "sadness", "despair", "